node {
   stage('init') {
      checkout scm
   }
   stage('build') {
      sh '''
         mvn -f ./complete/pom.xml clean package
         cd complete/target
         cp ../src/main/web.config web.config
         cp spring-boot-0.0.1-SNAPSHOT.jar app.jar 
         zip todo.zip app.jar web.config
      '''
   }
   stage('deploy') {
      azureWebAppPublish azureCredentialsId: env.AZURE_CRED_ID,
      resourceGroup: env.RES_GROUP, appName: env.WEB_APP, filePath: "**/todo.zip"
   }
}
