node {
   stage('init') {
      checkout scm
   }
   stage('build') {
      sh '''
         mvn -f ./complete/pom.xml clean package
         mkdir target
         cd target
         cp ../complete/src/main/web.config web.config
         cp todo-app-java-on-azure-1.0-SNAPSHOT.jar app.jar 
         zip todo.zip app.jar web.config
      '''
   }
   stage('deploy') {
      azureWebAppPublish azureCredentialsId: env.AZURE_CRED_ID,
      resourceGroup: env.RES_GROUP, appName: env.WEB_APP, filePath: "**/todo.zip"
   }
}
